# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: reorder-python-imports
        name: reorder-python-imports
        entry: reorder-python-imports
        language: system
        types: [python]
        args: [--py37-plus]
    -   id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [python]
        args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]
