version: '3'
services:
  getmatch-urlshortener-service:
    build:
      dockerfile: conf/Dockerfile
      context: ./
    command: gunicorn -b 0.0.0.0:9050 -w 2 --max-requests 1000 --timeout 30 service.app:app
    volumes:
      - type: bind
        source: ./src/
        target: /app
    networks:
      - getmatch-urlshortener-service-network
    env_file:
      - conf/env/app.dev.env
      - conf/env/db.dev.env
    ports:
      - 9050:9050

  service-db:
    image: mongo
    restart: "no"
    env_file:
      - conf/env/db.dev.env
    networks:
      - getmatch-urlshortener-service-network
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:

networks:
  getmatch-urlshortener-service-network:
